### ISSUE TITLE
Velocity indicator

### ISSUE THREAD

**Issue by YeOldeDM** [DCowboy/Star-Game#52]
Currently it feels like it's hard to get a sense of velocity and accelleration, particularly when there aren't any other objects on-screen.

How about a speed indicator somewhere on the screen, maybe nested somewhere on the edge of the mini-map?  The value of the actual numbers don't need to have any real-world analogue (it could read out in pixels/hour, it wouldn't really matter). You could also have some readout for acceleration or delta-v, to indicate how your current thrust is affecting your velocity.

**Comment by DCowboy** [comment]
That's a good idea. and fairly easy to implement too.
