### ISSUE TITLE
BUG: Ship selection screen exists in the game world

### ISSUE THREAD

**Issue by YeOldeDM** [DCowboy/Star-Game#54]
It doesn't seem to happen every time, but sometimes, after dying and respawning, the 'foreground' (that is the ships, text, and button) of the ship selection screen seems to be floating around in space!
As soon as the mouse enters one of the ships, the game crashes trying to get the explanation text for the ship.

**Comment by DCowboy** [comment]
I haven't experienced that at all, I'll try to duplicate it myself. is this happening in a certain area like in the nebulae?) If it's what I think it might be, then it's a simple fix.
